name: Profile README
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Use default GH_TOKEN for Action
      - name: Update README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('./README.md', 'utf8');
            // Content is already managed via push.
            console.log('README.md checked and up-to-date.');
